### ISSUE TITLE
DOCS to run a dev version locally - maybe docker/docker-compose setup 

### ISSUE THREAD

**Issue by thanhchinh** [heathhenley/RhodyCarCounter#4]
Amazing!!! Thank you for sharing useful information!  Can you teach how to run like you?

**Comment by heathhenley** [comment]
> Amazing!!! Thank you for sharing useful information! Can you teach how to run like you?

Hey, thanks! I wrote about this a little bit here: https://heathhenley.github.io/posts/yolo-all-the-traffic-cams/

As far as running it yourself, I haven't written the docs you would probably need to get started - but I intend to (maybe this weekend). 

If you only want to run the frontend:
1. clone repo
2. navigate to the frontend/traffic_count directory
3. run` npm install` - to install the dependencies
4. run  `npm start` - the start the dev server on localhost

Running the backend will require a little more work, I'll post here when I've documented it properly in more detail. I would like to set up docker / docker-compose to spin up everything needed to run locally and pull in some example data, but I haven't got to it yet 😃

In general the idea is:
- set the environment variables that are in this template: https://github.com/heathhenley/RhodyCarCounter/blob/main/backend/env-template.bat (you don't actually need the AWS ones unless you want to stick the images in an AWS bucket) --> the backend needs a database, I'm running postgres on railway.app, you could install locally or even use sqlite. The DB_CONNECT_STR for sqlite should be something like `"file:./db.sqlite"` which is simpler than postgres. 
- clone the repo and navigate to `backend/api`
- to run the api: (you need python 3.10 or higher)
    - create a venv to install the api dependencies `python -m venv api_env` and activate it `(run Scripts/activate`)
    - install the api dependencies with `python -m pip install -r requirements-api.txt`
    - run the api with `uvicorn api:app --reload` 
    - it uses FastAPI, and their docs are awesome (https://fastapi.tiangolo.com/)
- if you want to run the worker, I would create a separate virtual environment:
    - create a venv to install the api dependencies `python -m venv worker_env` and activate it `(run Scripts/activate`)
    - install the worker dependencies with `python -m pip install -r requirements-worker.txt`
    - run the worker with `python worker/traffic.py`

**Comment by thanhchinh** [comment]
I really appreciate it. i seen your file docker update. how can i run it? My open system win 10 and i used anaconda run yolov8. May be i change os ubuntu can be run it on one pc? May be change your code? May be you explant for me plzz? Thank you for everything.

**Comment by heathhenley** [comment]
So I just added this: https://github.com/heathhenley/RhodyCarCounter/blob/main/README.md#how-to-run-locally

If you install docker you can run everything with docker compose - it will install all the dependencies into docker containers. 

*As noted in there, the front end still points to the production API but that will be fixed soon. 

Happy coding, let me know what you end up building I look forward to checking it out!

**Comment by thanhchinh** [comment]
[log.txt](https://github.com/heathhenley/RhodyCarCounter/files/11070649/log.txt)
Thank you for your hard work. I run all in my docker and i send you my log. 
db_setup container  cannot run.
may be you fix it!

**Comment by thanhchinh** [comment]
i had ran container docker , I change something url: API = "http://localhost:5001/api/cameras/" in copy_data_dev_db.py, db_setup container not run and show 
![Capture1](https://user-images.githubusercontent.com/19984981/227765795-7fdb1669-4667-4637-941b-4a31b098832f.PNG)
-- i check file traffic.py in worker: S3_BUCKET = 'rhodycarcounter' what S3_BUCKER mean? AWS bucket - latest labelled image from each cam? I had 2 raspberry pi camera with protocol rtsp. how will i do? build S3_BUCKER container?

**Comment by heathhenley** [comment]
Ah sorry for the confusion - that URL should not be changed - the db_setup container just runs a script to copy the camera list from https://rhodycarcounter-production.up.railway.app/api/cameras - so that the local database will have some cameras in it. 

The URL I was referring to changing was in the front end, it's still set up to load the camera data from the endpoint above, but it would be better to use the local one so you can see your changes. You could search for it and replace it if you wanted to do that.

You don't need S3 really, yes it's an AWS bucket. I'm just using it to store the labelled files to make it easy it to access (the frontend displays them from the same bucket). The labelled images are also saved locally if there are no aws credentials so you can use them from there. 

It sounds like you are trying to do something different a little different - what are you trying to detect? What are you hoping to do / make?

**Comment by thanhchinh** [comment]
![Capture2](https://user-images.githubusercontent.com/19984981/227782175-d8e6f2e3-6de9-4fe2-a893-112d839aa27b.PNG)
I think I can do the same as you, using your code, but I don't know how? may be you help me?

**Comment by heathhenley** [comment]
So it sounds like you have your own cameras that you want to pull images from and detect something?

My "worker" (in traffic.py) downloads images from the traffic cam website (https://github.com/heathhenley/RhodyCarCounter/blob/main/backend/worker/traffic.py#L59). It loops through all the cameras in the database and downloads their latest image from the traffic cam website. You would want to switch that to get the images from your cameras somehow (https://github.com/heathhenley/RhodyCarCounter/blob/main/backend/worker/traffic.py#L48) .
It then puts the number of cars detected in a database. Also my model was trained on coco and then on data from traffic cameras. If you aren't detecting cars from traffic cams, you will want to load your own model and weights here (https://github.com/heathhenley/RhodyCarCounter/blob/main/backend/worker/traffic.py#L42).

The API connects to the database and makes the data about the traffic cameras and the car counts available. Again if you are detecting something else, you will have to change the database models (which describes the tables in the database) https://github.com/heathhenley/RhodyCarCounter/blob/main/backend/database/model.py and the API schema https://github.com/heathhenley/RhodyCarCounter/blob/main/backend/api/schema.py which describes the data that you will return in the API (they are very similar in this case). 

The frontend uses the API to get the data (eg https://rhodycarcounter-production.up.railway.app/api/cameras/?skip=0&limit=100&status=false) and display it. There is a lot in this case that is pretty specific to my application. 

Actually in general there is kind of a lot that is pretty specific to my application in this project. Maybe one of the templates mentioned here might be a better starting point for your project: https://fastapi.tiangolo.com/project-generation/ they are set up specifically to be a starting point for a new project.

Assuming your goal is to end up with something very similar to what I have set up in this project, and you're trying to detect cars,  then I would suggest: 
- run the project as is locally 
- make small changes one at a time to change it to fit your application, and to make sure you understand how everything fits together, for example: 
    - figure out how to get an image from your camera
    - then figure out how to run the model on your image instead
    - put the data in the database (maybe you need to modify the columns, etc, to fit you app)

If you are trying to do something a little different, it might be better to use this project as a general guide and set up your own project from scratch to make sure you understand what's going on. You will definitely learn a lot more too!

If I were to do that, I would first split it into pieces and figure out each piece: 
- get the data - your interface to your cameras, get and save an image from each camera
- process data - take your image, run your model on your images, get results
- store data - store the results however you want, I used a postgres database 
- make it available - this can be your api, it makes the data in your database available by GET requests (can be https://fastapi.tiangolo.com/, Flask, https://www.django-rest-framework.org/) 
- display - this uses your api to get data and then displays it (I used react)

**Comment by heathhenley** [comment]
I'm going to close this issue as it's not really related to the dev of this project. Feel free to continue to email me if you have questions though after you've made some progress!
